import 'package:flutter/material.dart';

ThemeData defineTheme({
  required Brightness brightness,
  required int primary,
  required int onPrimary,
  required int primaryContainer,
  required int onPrimaryContainer,
  required int secondary,
  required int onSecondary,
  required int secondaryContainer,
  required int onSecondaryContainer,
  required int tertiary,
  required int onTertiary,
  required int tertiaryContainer,
  required int onTertiaryContainer,
  required int error,
  required int onError,
  required int errorContainer,
  required int onErrorContainer,
  required int background,
  required int onBackground,
  required int surface,
  required int onSurface,
  required int outline,
  required int surfaceVariant,
  required int onSurfaceVariant,
}) {
  return ThemeData(
    useMaterial3: true,
    colorScheme: ColorScheme.fromSeed(
      brightness: brightness,
      seedColor: Color(primary),
      primary: Color(primary),
      onPrimary: Color(onPrimary),
      primaryContainer: Color(primaryContainer),
      onPrimaryContainer: Color(onPrimaryContainer),
      secondary: Color(secondary),
      onSecondary: Color(onSecondary),
      secondaryContainer: Color(secondaryContainer),
      onSecondaryContainer: Color(onSecondaryContainer),
      tertiary: Color(tertiary),
      onTertiary: Color(onTertiary),
      tertiaryContainer: Color(tertiaryContainer),
      onTertiaryContainer: Color(onTertiaryContainer),
      error: Color(error),
      onError: Color(onError),
      errorContainer: Color(errorContainer),
      onErrorContainer: Color(onErrorContainer),
      background: Color(background),
      onBackground: Color(onBackground),
      surface: Color(surface),
      onSurface: Color(onSurface),
      outline: Color(outline),
      surfaceVariant: Color(surfaceVariant),
      onSurfaceVariant: Color(onSurfaceVariant),
    ),
    scaffoldBackgroundColor: Color(background),
  );
}

var lightTheme = defineTheme(
  brightness: Brightness.light,
  primary: 0xFF225EA9,
  onPrimary: 0xFFFFFFFF,
  primaryContainer: 0xFFd6e3ff,
  onPrimaryContainer: 0xFF001b3c,
  secondary: 0xFF006874,
  onSecondary: 0xFFFFFFFF,
  secondaryContainer: 0xFF97f0ff,
  onSecondaryContainer: 0xFF001f24,
  tertiary: 0xFFa23f00,
  onTertiary: 0xFFFFFFFF,
  tertiaryContainer: 0xFFffdbcd,
  onTertiaryContainer: 0xFF351000,
  error: 0xFFBA1A1A,
  onError: 0xFFFFFFFF,
  errorContainer: 0xFFffdad6,
  onErrorContainer: 0xFF410002,
  background: 0xFFF8FDFF,
  onBackground: 0xFF001F25,
  surface: 0xFFF8FDFF,
  onSurface: 0xFF001F25,
  outline: 0xFF74777f,
  surfaceVariant: 0xFFe0e2ec,
  onSurfaceVariant: 0xFF43474e,
);

var darkTheme = defineTheme(
  brightness: Brightness.dark,
  primary: 0xFFa8c8ff,
  onPrimary: 0xFF003062,
  primaryContainer: 0xFF00468a,
  onPrimaryContainer: 0xFFd6e3ff,
  secondary: 0xFF4fd8eb,
  onSecondary: 0xFF00363d,
  secondaryContainer: 0xFF004f58,
  onSecondaryContainer: 0xFF97f0ff,
  tertiary: 0xFFffb595,
  onTertiary: 0xFF571e00,
  tertiaryContainer: 0xFF7c2e00,
  onTertiaryContainer: 0xFFffdbcd,
  error: 0xFFffb4ab,
  onError: 0xFF690005,
  errorContainer: 0xFF93000a,
  onErrorContainer: 0xFFffdad6,
  background: 0xFF001f25,
  onBackground: 0xFFa6eeff,
  surface: 0xFF001F25,
  onSurface: 0xFFa6eeff,
  outline: 0xFF8e9099,
  surfaceVariant: 0xFF43474e,
  onSurfaceVariant: 0xFFc4c6cf,
);
