import 'package:flutter/material.dart';

import '../../extensions/color_extensions.dart';

ThemeData defineTheme({
  required Brightness brightness,
  required String primary,
  required String onPrimary,
  required String primaryContainer,
  required String onPrimaryContainer,
  required String secondary,
  required String onSecondary,
  required String secondaryContainer,
  required String onSecondaryContainer,
  required String tertiary,
  required String onTertiary,
  required String tertiaryContainer,
  required String onTertiaryContainer,
  required String error,
  required String onError,
  required String errorContainer,
  required String onErrorContainer,
  required String background,
  required String onBackground,
  required String surface,
  required String onSurface,
  required String outline,
  required String surfaceVariant,
  required String onSurfaceVariant,
}) {
  return ThemeData(
    useMaterial3: true,
    colorScheme: ColorScheme.fromSeed(
      brightness: brightness,
      seedColor: ColorExtensions.fromHex(primary),
      primary: ColorExtensions.fromHex(primary),
      onPrimary: ColorExtensions.fromHex(onPrimary),
      primaryContainer: ColorExtensions.fromHex(primaryContainer),
      onPrimaryContainer: ColorExtensions.fromHex(onPrimaryContainer),
      secondary: ColorExtensions.fromHex(secondary),
      onSecondary: ColorExtensions.fromHex(onSecondary),
      secondaryContainer: ColorExtensions.fromHex(secondaryContainer),
      onSecondaryContainer: ColorExtensions.fromHex(onSecondaryContainer),
      tertiary: ColorExtensions.fromHex(tertiary),
      onTertiary: ColorExtensions.fromHex(onTertiary),
      tertiaryContainer: ColorExtensions.fromHex(tertiaryContainer),
      onTertiaryContainer: ColorExtensions.fromHex(onTertiaryContainer),
      error: ColorExtensions.fromHex(error),
      onError: ColorExtensions.fromHex(onError),
      errorContainer: ColorExtensions.fromHex(errorContainer),
      onErrorContainer: ColorExtensions.fromHex(onErrorContainer),
      background: ColorExtensions.fromHex(background),
      onBackground: ColorExtensions.fromHex(onBackground),
      surface: ColorExtensions.fromHex(surface),
      onSurface: ColorExtensions.fromHex(onSurface),
      outline: ColorExtensions.fromHex(outline),
      surfaceVariant: ColorExtensions.fromHex(surfaceVariant),
      onSurfaceVariant: ColorExtensions.fromHex(onSurfaceVariant),
    ),
    scaffoldBackgroundColor: ColorExtensions.fromHex(background),
  );
}

var lightTheme = defineTheme(
  brightness: Brightness.light,
  primary: '#225EA9',
  onPrimary: '#FFFFFF',
  primaryContainer: '#d6e3ff',
  onPrimaryContainer: '#001b3c',
  secondary: '#006874',
  onSecondary: '#FFFFFF',
  secondaryContainer: '#97f0ff',
  onSecondaryContainer: '#001f24',
  tertiary: '#a23f00',
  onTertiary: '#FFFFFF',
  tertiaryContainer: '#ffdbcd',
  onTertiaryContainer: '#351000',
  error: '#BA1A1A',
  onError: '#FFFFFF',
  errorContainer: '#ffdad6',
  onErrorContainer: '#410002',
  background: '#F8FDFF',
  onBackground: '#001F25',
  surface: '#F8FDFF',
  onSurface: '#001F25',
  outline: '#74777f',
  surfaceVariant: '#e0e2ec',
  onSurfaceVariant: '#43474e',
);

var darkTheme = defineTheme(
  brightness: Brightness.dark,
  primary: '#a8c8ff',
  onPrimary: '#003062',
  primaryContainer: '#00468a',
  onPrimaryContainer: '#d6e3ff',
  secondary: '#4fd8eb',
  onSecondary: '#00363d',
  secondaryContainer: '#004f58',
  onSecondaryContainer: '#97f0ff',
  tertiary: '#ffb595',
  onTertiary: '#571e00',
  tertiaryContainer: '#7c2e00',
  onTertiaryContainer: '#ffdbcd',
  error: '#ffb4ab',
  onError: '#690005',
  errorContainer: '#93000a',
  onErrorContainer: '#ffdad6',
  background: '#001f25',
  onBackground: '#a6eeff',
  surface: '#001F25',
  onSurface: '#a6eeff',
  outline: '#8e9099',
  surfaceVariant: '#43474e',
  onSurfaceVariant: '#c4c6cf',
);
